import { api } from "./client";
import type { MediaType } from "../types";

// shape of the response returned by the backend /recommend endpoint, the recommendations
// field is the raw text generated by Gemini
type RecommendationResponse = {
  recommendations: string;
};

// wrapper around the recommendation endpoint so the frontend can request new
// recommendations without dealing with the backend payload field names directly
export const recommendationsApi = {
  // calls POST /recommend with the user's query and media type and returns Gemini's text
  // Input: object with query string and a MediaType
  // Output: Promise resolving to a RecommendationResponse
  generate(input: { query: string; mediaType: MediaType }): Promise<RecommendationResponse> {
    return api.post<RecommendationResponse>(
      "/recommend",
      // remap mediaType to the snake_case field the FastAPI model expects
      { query: input.query, media_type: input.mediaType },
      { auth: true },
    );
  },
};
